name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: iftialmin10
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          color_snake: "#00ffff"
          color_dots: "#ff5f6d,#ffc371,#00f2fe,#4facfe,#43e97b"

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
